# Generated by Django 5.2 on 2025-06-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherApplication',
        ),
    ]
