### Login
POST http://127.0.0.1:8000/api/accounts/login/
Content-Type: application/json

{
    "username": "janedoe",
    "password": "StrongPass456!"
}

### USER DETAILS
GET http://127.0.0.1:8000/api/accounts/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDQ5MTcyLCJpYXQiOjE3NDYwNDg4NzIsImp0aSI6IjNiNDg5OGU2YWM5ZTQ3NTRhZmU1MGFlYTZkNWFlYWJlIiwidXNlcl9pZCI6Mn0.tAMGqTaQTo-HRK7gD9y5lf9uwp8UakPmoWKFWImbUB0

### USER DETAILS
GET http://127.0.0.1:8000/api/accounts/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTQ4NDg2LCJpYXQiOjE3NDU5NDgxODYsImp0aSI6ImYyYThmNzI0NWMwMzRlNjg4YWUxNDgyZDcwYTgxM2Y0IiwidXNlcl9pZCI6Mn0.8jfh0DnUNtKGFpKxFI0EqYFrXYachetDLa5r8tkBk4Y

### SIGN UP 
POST http://127.0.0.1:8000/api/accounts/signup/
Content-Type: application/json

{
  "username": "janedoe",
  "password": "StrongPass456!",
  "password2": "StrongPass456!",
  "email": "janedoe@example.com",
  "first_name": "Jane",
  "last_name": "Doe"
}

### UPDATE USER PROFILE
PUT http://127.0.0.1:8000/api/accounts/me/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDQ5MTcyLCJpYXQiOjE3NDYwNDg4NzIsImp0aSI6IjNiNDg5OGU2YWM5ZTQ3NTRhZmU1MGFlYTZkNWFlYWJlIiwidXNlcl9pZCI6Mn0.tAMGqTaQTo-HRK7gD9y5lf9uwp8UakPmoWKFWImbUB0


{
  "first_name": "Jane",
  "last_name": "Doe",
  "email": "janedoe_updated@example.com"
}

### CREATING A COURSE
POST http://127.0.0.1:8000/api/courses/courses/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NDQyOTc1LCJpYXQiOjE3NDg0NDI2NzUsImp0aSI6ImFiNDZjYjczNTBmYjQzNjY4YThjZGNmYjQ5OWU3YTcxIiwidXNlcl9pZCI6Mn0.U9BCC6_apKhTEHanAcmBdfiOL1LxVIhMtl5Ot9AthbY

{
  "name": "Django for Beginners",
  "description": "Learn Django from scratch",
  "price": 1499,
  "launch_date": "2025-06-01",
  "rating": 4,
  "level": "beginner",
  "category": "web-dev",
  "subcategory": "web-dev-django",
  "tags": [1, 2],
  "duration":5
}

### RETRIEVING A COURSE
GET http://127.0.0.1:8000/api/courses/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjIzNzgwLCJpYXQiOjE3NTA0NTA5ODAsImp0aSI6ImM1OWNjNDllMmUxYTRmNjg5YTBmMGI4M2E3NjhkOTdjIiwidXNlcl9pZCI6Mn0.UsXVORe40jQrAvdvpxb0p0jvw_OHkCtXaib6wmEOyKw


### Apply for a Certificate
POST http://127.0.0.1:8000/api/courses/certificates/apply/javascript-101-9c4c6a/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDU0NjEwLCJpYXQiOjE3NTAyODE4MTAsImp0aSI6IjZkY2FlNzk1OWE0NzRlYzZiNTQzMmNhNzNlMjViN2NlIiwidXNlcl9pZCI6M30.C9FgmkIQtTyNY1EEwXHatDc9jsJ6Um7EfSAbW89_ONc

### Approve the Certificate
POST http://127.0.0.1:8000/api/courses/certificates/approve/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMzYzNzkxLCJpYXQiOjE3NTAxOTA5OTEsImp0aSI6IjJmODQyZTBlNGY2YTRiZWI4YTJhOTUwMzIwYTU4ZTZiIiwidXNlcl9pZCI6Mn0.v5gv4Cig1KNFqVPQwDG99D2cYlKjYMeGAkLpaQXpT1o

### List all Pending Certificates to be Approved/Rejected
GET http://127.0.0.1:8000/api/courses/certificates/pending
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMzYzNzkxLCJpYXQiOjE3NTAxOTA5OTEsImp0aSI6IjJmODQyZTBlNGY2YTRiZWI4YTJhOTUwMzIwYTU4ZTZiIiwidXNlcl9pZCI6Mn0.v5gv4Cig1KNFqVPQwDG99D2cYlKjYMeGAkLpaQXpT1o

### Reject the Certificate
POST http://127.0.0.1:8000/api/courses/certificates/reject/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMzYzNzkxLCJpYXQiOjE3NTAxOTA5OTEsImp0aSI6IjJmODQyZTBlNGY2YTRiZWI4YTJhOTUwMzIwYTU4ZTZiIiwidXNlcl9pZCI6Mn0.v5gv4Cig1KNFqVPQwDG99D2cYlKjYMeGAkLpaQXpT1o
