# Generated by Django 5.2 on 2025-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_price_assignment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecontent',
            name='title',
            field=models.CharField(blank=True, default='Deafault Title for Content', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Article'), ('video', 'Video'), ('file', 'Document')], max_length=10),
        ),
    ]
