# Generated by Django 5.2 on 2025-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_modulecontent_title_alter_modulecontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
