# Generated by Django 5.2 on 2025-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_assignmentsubmission_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the course in INR', max_digits=10),
        ),
    ]
