# Generated by Django 5.2 on 2025-06-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_enrollment_access_granted_enrollment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
